-
  name: Scholar
  link: https://scholar.google.com/citations?user=bmOnRUcAAAAJ&hl=en

- 
  name: Twitter
  link: https://twitter.com/vlastelicap

-
  name: LinkedIn
  link: https://www.linkedin.com/in/mvlastelica/
-
  name: Medium
  link: https://medium.com/@marinvp